<?php
/*  Copyright notice
*  
*  (c) 2007 Patrick Broens (patrick@netcreators.com)
*  All rights reserved
*
*  This script is part of the TYPO3 project. The TYPO3 project is 
*  free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  The GNU General Public License can be found at
*  http://www.gnu.org/copyleft/gpl.html.
* 
*  This script is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  This copyright notice MUST APPEAR in all copies of the script!
***************************************************************/

require_once (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('nc_pbsurveyfesimplestats') . 'lib/class.tx_ncpbsurveyfesimplestats_questions.php');
require_once (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('nc_pbsurveyfesimplestats') . 'lib/class.tx_ncpbsurveyfesimplestats_results.php');
require_once (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('nc_pbsurveyfesimplestats') . 'lib/class.tx_ncpbsurveyfesimplestats_view.php');

/**
 * Frontend Module for the 'nc_pbsurveyfesimplestats' extension.
 *
 * @author Patrick Broens <patrick@netcreators.com>
 * @package TYPO3
 * @subpackage nc_orgchart
 */
class tx_ncpbsurveyfesimplestats_pi1 extends \TYPO3\CMS\Frontend\Plugin\AbstractPlugin {
	
	var $prefixId = 'tx_ncpbsurveyfesimplestats_pi1';
	var $scriptRelPath = 'pi1/class.tx_ncpbsurveyfesimplestats_pi1.php';
	var $extKey = 'nc_pbsurveyfesimplestats';
	var $aConf = array();
    
    /**********************************
	 *
	 * Configuration functions
	 *
	 **********************************/

	/**
	 * All needed configuration values are stored in the member variable $this->arrConfig and the template code goes in $this->arrConfig['templateCode'] .
	 *
	 * @param	array		Configuration array from TS
	 * @return	void
	 */
	function init($aConf) {
		$this->aConf = $aConf; // Storing configuration as a member var
		$this->pi_setPiVarDefaults();
		$this->pi_loadLL();
		$this->url = $this->pi_getPageLink($GLOBALS['TSFE']->id,$GLOBALS['TSFE']->sPre); //Current URL
		$this->pid = $this->cObj->data['pages'] ? $this->cObj->data['pages'] : $this->aConf['pid'];
	}
    
    /**********************************
	 *
	 * General functions
	 *
	 **********************************/
	 
	/**
	 * Calls the init() function to setup the configuration, 
	 * reads the database and renders the output
	 *
	 * @param	string		Function output is added to this
	 * @param	array		Configuration array
	 * @return	string		Complete content generated by the plugin
	 */
	function main($sContent,$aConf)	{
		$this->init($aConf);

		$questions = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('tx_ncpbsurveyfesimplestats_questions');
		$questions->setSurveyPid($this->pid);
		$questions->done();
		
		$results = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('tx_ncpbsurveyfesimplestats_results');
		$results->setSurveyPid($this->pid);
		$results->done();
		
		$view = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('tx_ncpbsurveyfesimplestats_view');
		$view->setCaller($this);
		$view->setConfiguration($this->aConf);
		$view->setRespondents($results);
		$view->setQuestions($questions);
		$sHtml = $view->done();

        $sHtml = $this->pi_wrapInBaseClass($sHtml);
		return $sHtml;
	}
}